version: '3.9'

services:
  app:
    build: .
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_URI=${NEO4J_URI}
    volumes:
      - ./data:/kg_library/data
      - ./models:/kg_library/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  neo4j:
    image: neo4j:5.26.3
    container_name: neo4j_container
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data
    ports:
      - "7474:7474"  # HTTP-интерфейс Neo4j
      - "7687:7687"  # Bolt-протокол
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:7474" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  neo4j_data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450