version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  app:
    build: .
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}

volumes:
  neo4j_data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450